services:
  - type: web
    name: alexa-skill-server
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app --bind 0.0.0.0:10000
    plan: free
    envVars: []
